spring:
  datasource:
    url: jdbc:mysql://localhost:3306/red_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: '!Aa0137989720'
  redis:
    #    host: localhost # Redis服务器地址
    #    database: 0 # Redis数据库索引（默认为0）
    #    port: 6379 # Redis服务器连接端口
    #    password: # Redis服务器连接密码（默认为空）
    #    timeout: 3000ms # 连接超时时间（毫秒）
    host: 36.26.69.161 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #    password: '!Aa0137989720' # Redis服务器连接密码（默认为空）
    password: '123456' # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
  logging:
    level:
      root: info

  elasticsearch:
    uris: 36.26.69.161:9200


aliyun:
  sts:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    #    endpoint: oss-accelerate.aliyuncs.com
    ki: LTAI5t6QoGkprnCHxVprT6j2
    ks: q7qQ9W7WDg0mfHR4IrtdIqgcuqbdHt
    #bucket可以在控制台创建，也可以使用java代码创建
    bucketname: franky123
    roleArn: acs:ram::1961627345815863:role/ramosstest
  vod:
    ki: LTAI5tFeHEvGrfLwpA2hJxhX
    ks: pD0nHpS9js7AZNGwhiUrh1VLU6BF3U
    templateGroupId: 5969d075d72bebf65b39670f019ed6ed #转码模板组id
    workflowId: b2cde7eaf99a895b89ab1a88abee0a25 #工作流id

elasticsearch:
  http: "36.26.69.161:9200"

#Netty的一些配置
netty:
  timeout: 6000
  port: 9000
  #多端口绑定
  portSalve: 9001
